version: '3'
services:
  api:
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      PORT: 5000
  nginx:
    depends_on:
      - api
    expose:
      - 80
    environment: 
      VIRTUAL_HOST: hcaptcha.wmtech.cc
      LETSENCRYPT_HOST: hcaptcha.wmtech.cc
      LETSENCRYPT_EMAIL: swmeng@yes.my
    build:
      context: ./nginx
    restart: unless-stopped
    container_name: hcaptcha-nginx


networks:
    default:
        external:
            name: nginx-proxy
